# Generated by Django 5.2.7 on 2025-10-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_admin_reviewer",
            field=models.BooleanField(default=False),
        ),
    ]
