# Generated by Django 5.2.7 on 2025-10-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("national_id", models.CharField(max_length=50, unique=True)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("marital_status", models.CharField(blank=True, max_length=20)),
                ("phone_number", models.CharField(blank=True, max_length=100)),
                (
                    "alternate_phone_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("sub_county", models.CharField(blank=True, max_length=100)),
                ("ward", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("physical_address", models.TextField(blank=True)),
                ("employment_status", models.CharField(blank=True, max_length=50)),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "work_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("other_income_source", models.CharField(blank=True, max_length=100)),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "other_income_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("consent_credit_check", models.BooleanField(default=False)),
                ("consent_data_processing", models.BooleanField(default=False)),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("business_type", models.CharField(blank=True, max_length=100)),
                ("business_location", models.CharField(blank=True, max_length=255)),
                (
                    "business_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("business_age", models.CharField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=400)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("mpesaNumber", models.CharField(blank=True, max_length=50)),
                ("accepted_terms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("term_months", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="loan_application_module.client",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NextOfKin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_of_kin",
                        to="loan_application_module.client",
                    ),
                ),
            ],
        ),
    ]
