# Generated by Django 5.2.7 on 2025-10-23 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_application_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_applications",
                to="loan_application_module.client",
            ),
        ),
    ]
