# Generated by Django 5.2.7 on 2025-10-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_application_module", "0003_loanrepayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanrepayment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_repayments",
                to="loan_application_module.loanapplication",
            ),
        ),
    ]
