# Generated by Django 5.2.7 on 2025-10-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_application_module", "0004_alter_loanrepayment_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="daily_repayment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="interest_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="interest_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="loan_purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="total_payable",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="loan_application_module.client",
            ),
        ),
    ]
